const data = {
  produtos: [
    {
      _id: '1',
      name: 'Veneziana 6 folhas 1,00 x 1,00',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 356,
      rating: '4.5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '2',
      name: 'Veneziana 6 folhas 1,00 x 1,20',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 396,
      rating: '5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '3',
      name: 'Veneziana 6 folhas 1,00 x 1,50',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 415,
      rating: '3.5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '4',
      name: 'Veneziana 6 folhas 1,00 x 2,00',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 450,
      rating: '2',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '5',
      name: 'Veneziana 6 folhas 1,20 x 1,20',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 520,
      rating: '5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '6',
      name: 'Veneziana 6 folhas 1,20 x 1,50',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 545,
      rating: '5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
    {
      _id: '7',
      name: 'Veneziana 6 folhas 1,20 x 2,00',
      category: 'Venezianas',
      image: '../images/veneziana-6-folhas-de-aluminio-branco-com-grade.jpg',
      price: 605,
      rating: '2.5',
      description: 'Veneziana 6 folhas de alumínio branco com grade 1,00 x 1,00',
    },
  ]
}
export default data;